name: Deploy para Locaweb via FTP

on:
  push:
    branches:
      - main # Ou 'master', dependendo do nome da sua branch principal

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      # Se o seu projeto precisa de build (React, Vite, Node, etc.),
      # você pode descomentar e ajustar as linhas abaixo:
      # - name: Instalar dependências e rodar Build
      #   run: |
      #     npm install
      #     npm run build

      - name: Sincronizar arquivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/ # Ajuste a pasta destino da Locaweb (ex: /public_html/ ou /web/)
